### ISSUE TITLE
I want to test the uploader

### ISSUE THREAD

**Issue by dong-y** [tidepool-org/chrome-uploader#118]
What should I specify as e-mail and password?

**Comment by jebeck** [comment]
The only way to test the uploader currently is to run our entire platform locally (and you must then have either a CareLink account or one of the devices the uploader currently reads data from). When you're running the whole platform locally, you'll be able to create an account in [blip](https://github.com/tidepool-org/blip 'blip'). The instructions for getting the entire platform running locallly are [here](http://developer.tidepool.io/starting-up-services/).

You can also drop in our [Gitter chat](https://gitter.im/tidepool-org/chat) with questions.
