### ISSUE TITLE
several problems with european medtronic files

### ISSUE THREAD

**Issue by PieterGit** [tidepool-org/chrome-uploader#124]
i tried importing a european medtronic file with chrome-uploader/lib/carelink/cli/csv_loader.js and I had several issues:

ISSUE-1: medtronic csv export fileformat from carelink.minimed.eu is different if you have another language selected in your user preferences:

E.g. English header
Index,Date,Time,Timestamp,New Device Time,BG Reading (mmol/L),Linked BG Meter ID,Temp Basal Amount (U/h),Temp Basal Type,Temp Basal Duration (hh:mm:ss),Bolus Type,Bolus Volume Selected (U),Bolus Volume Delivered (U),Bolus Duration (hh:mm:ss),Prime Type,Prime Volume Delivered (U),Suspend,Rewind,BWZ Estimate (U),BWZ Target High BG (mmol/L),BWZ Target Low BG (mmol/L),BWZ Carb Ratio (grams),BWZ Insulin Sensitivity (mmol/L),BWZ Carb Input (grams),BWZ BG Input (mmol/L),BWZ Correction Estimate (U),BWZ Food Estimate (U),BWZ Active Insulin (U),Alarm,Sensor Calibration BG (mmol/L),Sensor Glucose (mmol/L),ISIG Value,Daily Insulin Total (U),Raw-Type,Raw-Values,Raw-ID,Raw-Upload ID,Raw-Seq Num,Raw-Device Type

If you change your language prefence to Dutch you get: 
Index,Datum,Tijd,Tijdstempel,Nieuwe apparaattijd,BG-meetwaarde (mmol/l),ID gekoppelde BG-meter,Tijdel. basaalsnelheid (E/H),Tijdel. basaaltype,Tijdel. basaalduur (hh:mm:ss),Bolustype,Geselecteerd bolusvolume (E),Afgegeven bolusvolume (E),Bolusduur (hh:mm:ss),Vultype,Afgegeven vulvolume (E),Stoppen,Terugdraaien,Bolus Wizard-schatting (E),Bolus Wizard streef-BG hoog (mmol/l),Bolus Wizard streef-BG laag (mmol/l),Bolus Wizard KH-ratio (gram),Bolus Wizard insulinegevoeligheid (mmol/l),Bolus Wizard KH-invoer (gram),Bolus Wizard BG-invoer (mmol/l),Bolus Wizard geschatte correctiebolus (E),Bolus Wizard geschatte maaltijdbolus (E),Bolus Wizard actieve insuline (E),Alarm,Sensorkalibratie-BG (mmol/l),Sensorglucose (mmol/l),ISIG-waarde,Insuline-dagtotaal (E),Onbewerkt: type,Onbewerkt: waarden,Onbewerkt: ID,Onbewerkt: upload-ID,Onbewerkt: volgnummer,Onbewerkt: apparaattype

I assume you won't support other languages than English. Be sure to warn European users of this issue.

ISSUE-2: even with language on English, my medtronic export uses "," instead of "." as a seperator for real values. E.g. RATE=0,9 instead of RATE=0.9.
BasalProfileStart,"PATTERN_NAME=standard, PROFILE_INDEX=0, RATE=0,9, START_TIME=0, ACTION_REQUESTOR=pump"

ISSUE-3: Unfortuately, when I fix this in the input csv file (regexp in VI :%s/\([A-Z_][A-Z]*\)=\([\-0-9][0-9]*\),\([\-0-9][0-9]* \)/\1=\2.\3/g) I still encounter problems, such as:

CareLink CLI: Loading CareLink CSV...
No local session found
POST /auth/login
Session saved
CareLink CLI: Loading using the timezone CET
CareLink CLI: Loading for user  xxx
CareLink CLI: Reading /xxx/CareLink-Export-test-uk.csv
CareLink CLI: Error processing CareLink data: { [TypeError: Cannot read property 'start' of undefined] step: 'processData' }
TypeError: Cannot read property 'start' of undefined
    at processParts (/home/xxx/tidepool-org/chrome-uploader/lib/carelink/carelinkSimulator.js:221:38)
    at pushBasalClockForward (/home/xxx/tidepool-org/chrome-uploader/lib/carelink/carelinkSimulator.js:299:14)
    at Object.basalScheduled (/home/xxx/tidepool-org/chrome-uploader/lib/carelink/carelinkSimulator.js:366:7)
    at Array.3 (/home/xxx/tidepool-org/chrome-uploader/lib/carelink/basal.js:60:21)
    at /home/pieterb/tidepool-org/chrome-uploader/lib/drivers/carelinkDriver.js:331:28
    at Array.forEach (native)
    at Object.processData (/home/xxx/tidepool-org/chrome-uploader/lib/drivers/carelinkDriver.js:323:38)
    at processData (/home/xxx/tidepool-org/chrome-uploader/lib/driverManager.js:135:16)
    at fn (/home/pieterb/tidepool-org/chrome-uploader/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/home/xxx/tidepool-org/chrome-uploader/node_modules/async/lib/async.js:557:34)

Any clue how to fix this?

**Comment by jebeck** [comment]
@PieterGit unfortunately at the moment we don't have the resources to work on international support for CareLink. However, we absolutely welcome pull requests from the open-source community to this end. Our dream is to be completely international one day!

As to debugging this particular processing issue, it looks like an issue with the basal processing, but I can't tell much more without seeing the raw data. If this is an older Medtronic pump - 522/722 or below - there could be substantial issues; we don't fully support those older pumps, as there are significant differences in the CSV data, particular with respect to the basals.

Filed on Trello [here](https://trello.com/c/tMm7vpl7).
