### ISSUE TITLE
whishlist: medtronic csv upload feature in the web frontend instead of providing medtronic credentials

### ISSUE THREAD

**Issue by PieterGit** [tidepool-org/chrome-uploader#125]
I rather have a medtronic csv upload feature in the chrome uploader than to provide my medtronic credentials to tidepool. You write you don't store the credentials, but asking for users username/password is considered a bad security practice.

Please provide a web frontend, similar to the chrome-uploader/lib/carelink/cli/csv_loader.js feature.

**Comment by jebeck** [comment]
Thanks for the suggestion @PieterGit 

I've filed this on our Trello board for backlog items [here](https://trello.com/c/egJZundn). (We use Trello instead of GitHub issues for our project tracking, so I'm also closing the issue here.)
