### ISSUE TITLE
Question: Additional Uses of TandemDriver.js

### ISSUE THREAD

**Issue by dennisgove** [tidepool-org/chrome-uploader#252]
Please let me know if you'd rather this question come in in a different way.

Is it possible to use https://github.com/tidepool-org/chrome-uploader/blob/master/lib/drivers/tandemDriver.js to send commands to a t:slim? I'd specifically like to send commands to my own pump to begin a bolus.

**Comment by jebeck** [comment]
Hi @dennisgove 

This is a fine way to ask the question, and thanks for the interest! Our driver does not include that functionality.
