### ISSUE TITLE
Queston: Running testDriver.js against tandemDriver.js with t:slim attached

### ISSUE THREAD

**Issue by dennisgove** [tidepool-org/chrome-uploader#253]
I'd like to do a test run of the tandemDriver.js against a connected t:slim. I found testDriver.js but cannot quite see how I'd kick that off with the tandemDriver. Is this possible?

**Comment by jebeck** [comment]
@gniezen can you field this one? I'm not sure I've ever used the testDriver.js myself (and it's possible it is out-of-date/broken/deprecated).

**Comment by gniezen** [comment]
Hi @dennisgove ! `testDriver.js` looks indeed to be out-of-date/deprecated and doesn't actually test specific drivers, but the driver sequence. What exactly is it that you would like to do?

**Comment by dennisgove** [comment]
Thanks. That's what it looked like to me as well.

What I'd like to do is run tandemDriver.js independently so I can mess around with it without worrying about any of the other pieces.

**Comment by gniezen** [comment]
While it's possible to run parts of the driver code (e.g. `tandem/tandemSimulator.js`, which can be tested using `test/node/tandem/testTandemSimulator.js`) independently, we don't yet have a test that can independently test the parts that actually talk to the pump.

**Comment by dennisgove** [comment]
I see. Thank you.
