### ISSUE TITLE
Chrome App Migration?

### ISSUE THREAD

**Issue by bgiesing** [tidepool-org/chrome-uploader#323]
In case you haven't seen yet @gniezen, Google is discontinuing Chrome apps on every platform except Chrome OS. Any plans for this? Google says devs should convert it to either Progressive Web Apps or native packaging with Electron/NW.js.

https://developers.chrome.com/apps/migration

**Comment by gniezen** [comment]
Hi @bgiesing ! Yeah, I saw the notice just before midnight on Friday and didn't sleep well at all afterwards ;) We're still evaluating all the options:

- NW.js [just announced](http://nwjs.io/blog/chrome-apps-support/) that they will be supporting the `chrome.*` APIs (we currently require the `chrome.serial` and  `chrome.hid` USB libraries). 
- If we end up using Electron we'll have to switch to using the Node USB/serial libraries. 
- I quite like the idea of turning the Uploader into a web app, but that would require browsers to support Google's [WebUSB API](https://wicg.github.io/webusb/) - looks like Chrome will start supporting it in [version 54](https://www.chromestatus.com/feature/5651917954875392).

**Comment by gniezen** [comment]
Closing this issue as we have migrated to an Electron app with v2.0.
