### ISSUE TITLE
SMBGs don't appear for 670G

### ISSUE THREAD

**Issue by pazaan** [tidepool-org/chrome-uploader#452]
### Description
When downloading pump data from a 670G series device, the SMBG's don't appear in the trend view or daily view.

### Environment
**Uploader version**: 0.310.0-alpha.11.135.gb0298b2e
**OS**: macOS

**Comment by pazaan** [comment]
Create QA build version 0.310.0-alpha.11.149.g3ef0b6be to test

**Comment by eluhrs** [comment]
Fix confirmed.  Looks good.
![screen shot 2017-08-04 at 12 21 15 pm](https://user-images.githubusercontent.com/825578/28977292-73e16394-790f-11e7-8bbf-42526606be76.png)
