### ISSUE TITLE
Unable to upload Dexcom G5; device unsupported?

### ISSUE THREAD

**Issue by clenk** [tidepool-org/chrome-uploader#570]
### Issue
I tried to upload from my Dexcom G5 receiver but got the following error:

> Upload Failed: Something went wrong during device upload
Details: Sorry, we don't support this device yet | UTC Time: 2018-02-11T07:51:32-05:00 | Name: Error | Code: E_DEVICE_UPLOAD | undefined: [object Object] | Stack Trace: parse_egv_records, Object.headerParser [as parser]

### What I tried
I've tried with both v2.2.4 and v2.2.5 with the same results. The receiver shows that it is charging. I tried a couple different USB cables, including the one that came with the Dexcom. I'm on Windows 10 and updated with the latest Windows Update. Still no luck.

**Comment by krystophv** [comment]
Hi Chris. We’re still working with Dexcom to get the device protocols for their new touchscreen receiver. Can you send a message to support@tidepool.org requesting you be notified when we update the Uploader to support that device and our Community Manager will let you know when we’ve updated our software?

**Comment by clenk** [comment]
Thanks for the reply! I was confused because [this page](http://support.tidepool.org/article/13-upload-your-dexcom-g4) specifically mentioned the G5. Was there an older version of the receiver that worked?

I'll send an email.

**Comment by krystophv** [comment]
Yes, there was a version of the G5 receiver that looked just like a G4 receiver that used the same protocol spec. They updated the protocol a bit when they moved over to the touchscreen receiver.
