### ISSUE TITLE
Add Medtronic device 754 as supported device

### ISSUE THREAD

**Issue by mgentile** [tidepool-org/chrome-uploader#585]
Hi guys,
first of all, thank you for this amazing tool!
I am the owner of a Medtronic device version 754 and I could not believe it was not supported for uploading data through the Bayer Counter Next Link.
Therefore I have decided to clone the repo and add it to the list of supported devices and try. All data has been uploaded with no errors and it looks good and correct.
Can we add it to the list of supported devices, so other owners of the 754 model can also be allowed to use this uploader?

Thanks,
Massimiliano

**Comment by francescaneri** [comment]
Hi, I too have a 523 and I have the same problem.
Details: Could not open connection to pump. Please try again. | UTC Time: 2018-03-18T16:05:37+01:00 | Name: Error | Code: E_MEDTRONIC_UPLOAD | undefined: [object Object] | Stack Trace: parser, decodeMessage, replenish, iterateeCallback

thanks
Matteo Neri

**Comment by krystophv** [comment]
If you could, please head to https://support.tidepool.org/ and use the `Contact` form to send the device addition request in as that's where we try and track all the requests that come in and, subsequently, notify users when the device becomes available. I do know that the 754 is relatively high on the list of priorities.

**Comment by mgentile** [comment]
I have asked for the device addition in https://support.tidepool.org/ and received a very nice reply from Chris Snider, so it is useless to keep this issue open.
