### ISSUE TITLE
medtronic 523 error tidepool uploader

### ISSUE THREAD

**Issue by francescaneri** [tidepool-org/chrome-uploader#586]
Hi, I too have a medtronic 523.
Details: Could not open connection to pump. Please try again. | UTC Time: 2018-03-18T16:05:37+01:00 | Name: Error | Code: E_MEDTRONIC_UPLOAD | undefined: [object Object] | Stack Trace: parser, decodeMessage, replenish, iterateeCallback

thanks
Matteo Neri

**Comment by pazaan** [comment]
Hey @francescaneri. Do you have any further details? Are you able to send us a console log file?

**Comment by francescaneri** [comment]
Hi, 
I leave my credentials:
m.neri1973@gmail.com
Password: Celiaco_2010

Loop use: I still can not download data directly but only from carelink.

Matteo

**Comment by krystophv** [comment]
@francescaneri please, for your own safety, never put a password in a public forum on the internet. It might be best if you use a more secure communication channel via our official support at https://support.tidepool.org/ using the `Contact` tab

**Comment by pazaan** [comment]
Uploading via CareLink is no longer supported.
