### ISSUE TITLE
Add Support for Nippro brand meters

### ISSUE THREAD

**Issue by rmhollid** [tidepool-org/chrome-uploader#588]
Please add support for Nippro devices like
TrueMetrix
TrueMetrix Air

A majority of patients we see use these devices and it would be a great help if they were supported.

**Comment by krystophv** [comment]
I believe there is some work in progress for this in this branch: https://github.com/tidepool-org/chrome-uploader/tree/truemetrix
being tracked in this Trello card: https://trello.com/c/OFkyZUe6/335-uploader-trividia-true-metrix

**Comment by gniezen** [comment]
Support for True Metrix, True Metrix Air and True Metrix Go added in v2.6.0.
