### ISSUE TITLE
One Touch Ultra 2 Failed upload

### ISSUE THREAD

**Issue by rmhollid** [tidepool-org/chrome-uploader#593]
One touch Ultra 2 

Details: TIMEOUT | UTC Time: 2018-04-03T09:38:03-04:00 | Name: Error | Code: E_DEVICE_UPLOAD | undefined: [object Object] | Stack Trace: binding.close.then

Second Attempt

Details: TIMEOUT | UTC Time: 2018-04-03T09:39:05-04:00 | Name: Error | Code: E_DEVICE_UPLOAD | undefined: [object Object] | Stack Trace: binding.close.then

Failure repeated with both legacy cable and new cable. 
Failure repeated on multiple workstations 
Test meter without data will upload without fail

OS: Windows 10

**Comment by rmhollid** [comment]
To Clarify this is happening to all patient One touch ultra 2 we attempt to download.

**Comment by rmhollid** [comment]
Details: TIMEOUT | UTC Time: 2018-04-10T10:34:57-04:00 | Name: Error | Code: E_DEVICE_UPLOAD | undefined: [object Object] | Stack Trace: binding.close.then

**Comment by rmhollid** [comment]
This issue is still prevalent. Are there any developments on this?

**Comment by gniezen** [comment]
A fix was just released as part of Uploader v2.6.2. @rmhollid Please give it a spin at let me know how it goes!
