### ISSUE TITLE
Tidepool Uploader 2.5.4 reports error on Carelink Credentials even though credentials are correct

### ISSUE THREAD

**Issue by mfdieckmann** [tidepool-org/chrome-uploader#596]
After update to version 2.5.4, Tidepool Uploader reports this error on uplink from Carelink:

Upload Failed: Check your CareLink username and password
Hide details
UTC Time: 2018-04-06T13:42:39-05:00 | Code: E_CARELINK_CREDS | Version: 2.5.4

Even though I am entering valid Carelink username and password.  Worked previous to this latest update.

**Comment by gniezen** [comment]
CareLink import option was removed in Uploader v2.5.11
