### ISSUE TITLE
No control over Installation Files

### ISSUE THREAD

**Issue by penngos** [tidepool-org/chrome-uploader#607]
Very typical of Healthcare software - no ability to control the apps installation, no silent installation option for the USB drivers.  You make it difficult for IT workers within Healthcare to use your product without tearing it open and re-writing it for our own environment.  It's very frustrating.  It might be easier for you to use the NSIS script compiler, but that doesn't work for us.

**Comment by gniezen** [comment]
Note that a silent USB driver install is not possible on Windows 7 without a hotfix (which was never made available on Windows Update): https://support.microsoft.com/en-us/help/2921916/the-untrusted-publisher-dialog-box-appears-when-you-install-a-driver-i

Given that the hotfix requires a restart for it to work and that we probably can't distribute it with the installer, having a silent install on Windows 7 is not viable. I'm going to attempt to allow a silent install for Windows 8, 8.1 and 10, and provide an error message if a silent install is attempted on Windows 7.

**Comment by gniezen** [comment]
A silent install option (`/S`) is now available in v2.8.6, which includes installing the USB drivers silently.
