### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by pradeepjaladi** [tidepool-org/chrome-uploader#728]
Hi All,

npm install was failling in both linux ( ubuntu 18) and windows 10. Let me know who to run the chrome-uploaded locally.

**Comment by pazaan** [comment]
Are you able to provide the output of the failure?

**Comment by pradeepjaladi** [comment]
Here is the log details

jalad@DESKTOP-E6OTOI1 MINGW64 /d/~Development/Source/diabetes/chrome-uploader (master)
$ npm install

> electron-chromedriver@1.8.0 install D:\~Development\Source\diabetes\chrome-uploader\node_modules\electron-chromedriver
> node ./download-chromedriver.js

successfully dowloaded and extracted!

> usb@1.3.2 install D:\~Development\Source\diabetes\chrome-uploader\node_modules\usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[usb] Success: "D:\~Development\Source\diabetes\chrome-uploader\node_modules\usb\src\binding\usb_bindings.node" is installed via remote

> drivelist@6.2.2 install D:\~Development\Source\diabetes\chrome-uploader\node_modules\drivelist
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.12.0 runtime=node arch=x64 platform=win32)

D:\~Development\Source\diabetes\chrome-uploader\node_modules\drivelist>if not defined npm_config_node_gyp (node "D:\~Development\Tools\nvm-noinstall\v8.12.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\~Development\Tools\nvm-noinstall\v8.12.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\jalad\.windows-build-tools\python27\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\~Development\Tools\nvm-noinstall\v8.12.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\~Development\Tools\nvm-noinstall\v8.12.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at D:\~Development\Tools\nvm-noinstall\v8.12.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\~Development\\Tools\\nvm-noinstall\\v8.12.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\~Development\Source\diabetes\chrome-uploader\node_modules\drivelist
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN The package eslint-plugin-lodash is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! drivelist@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the drivelist@6.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jalad\AppData\Roaming\npm-cache\_logs\2018-11-14T14_06_07_165Z-debug.log

jalad@DESKTOP-E6OTOI1 MINGW64 /d/~Development/Source/diabetes/chrome-uploader (master)


jalad@DESKTOP-E6OTOI1 MINGW64 /d/~Development/Source/diabetes/chrome-uploader (master)
$ node -v
v8.12.0

**Comment by pradeepjaladi** [comment]
i am able to get it working, Installed visual studio and other tools

**Comment by pazaan** [comment]
Just to round this out for anyone who Googles this. It appears that Node-gyp requires Python to be installed in order to build the dependencies.
