### ISSUE TITLE
Package building is failing

### ISSUE THREAD

**Issue by pradeepjaladi** [tidepool-org/chrome-uploader#731]
When i tried to build package it is failing, i tried both package-all & package-win. 
**Here is the log**
jalad@DESKTOP-E6OTOI1 MINGW64 /d/~Development/Source/diabetes/chrome-uploader (master)
$ npm run package-win

> tidepool-uploader@2.8.4 package-win D:\~Development\Source\diabetes\chrome-uploader
> npm run build && electron-builder --win --x64

> tidepool-uploader@2.8.4 build D:\~Development\Source\diabetes\chrome-uploader
> npm run build-main && npm run build-renderer

> tidepool-uploader@2.8.4 build-main D:\~Development\Source\diabetes\chrome-uploader
> yarn build-main-quiet --progress --profile --colors

yarn run v1.12.1
warning package.json: "dependencies" has dependency "eslint-plugin-lodash" with range "2.5.0" that collides with a dependency in "devDependencies" of the same name with version "2.7.0"
$ cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.electron.js --progress --profile --colors
4097ms building modules
15ms sealing
16ms optimizing
0ms basic module optimization
0ms module optimization
0ms advanced module optimization
0ms basic chunk optimization
0ms chunk optimization
0ms advanced chunk optimization
0ms module and chunk tree optimization
0ms chunk modules optimization
0ms advanced chunk modules optimization
0ms module reviving
0ms module order optimization
0ms module id optimization
16ms chunk reviving
0ms chunk order optimization
15ms chunk id optimization
31ms hashing
0ms module assets processing
47ms chunk assets processing
0ms additional chunk assets processing
0ms recording
0ms additional asset processing
973ms chunk asset optimization
0ms asset optimization
359ms emitting
Hash: c6e28253317077503921
Version: webpack 3.8.1
Time: 5569ms
            Asset     Size  Chunks                    Chunk Names
    ./app/main.js  3.49 MB       0  [emitted]  [big]  main
./app/main.js.map  4.01 MB       0  [emitted]         main
 [130] (webpack)/buildin/module.js 495 bytes {0} [built]
       [] -> factory:390ms building:63ms = 453ms
 [143] ./app/actions/sync.js 291 kB {0} [built]
       [] -> factory:393ms building:297ms dependencies:94ms = 784ms
 [341] ./app/constants/actionTypes.js 9.7 kB {0} [built]
       [] -> factory:219ms building:578ms = 797ms
 [342] ./app/constants/actionSources.js 7.58 kB {0} [built]
       [] -> factory:219ms building:515ms = 734ms
 [343] ./app/constants/metrics.js 4.54 kB {0} [built]
       [] -> factory:219ms building:453ms = 672ms
 [344] ./app/actions/utils.js 4.81 kB {0} [built]
       [] -> factory:203ms building:125ms dependencies:47ms = 375ms
 [345] ./lib/core/personUtils.js 1.28 kB {0} [built]
       [] -> factory:219ms building:406ms dependencies:172ms = 797ms
 [349] multi babel-polyfill ./app/main.development 40 bytes {0} [built]
        factory:0ms building:0ms = 0ms
 [552] ./app/main.development.js 12.7 kB {0} [built]
       [] -> factory:157ms building:312ms = 469ms
 [670] ./app/actions/index.js 6.23 kB {0} [built]
       [] -> factory:188ms building:109ms = 297ms
 [671] ./app/actions/async.js 52.6 kB {0} [built]
       [] -> factory:909ms building:375ms dependencies:562ms = 1846ms
 [700] ./app/constants/otherConstants.js 3.16 kB {0} [built]
       [] -> factory:312ms building:78ms = 390ms
 [701] ./app/utils/errors.js 8.83 kB {0} [built]
       [] -> factory:203ms building:156ms dependencies:0ms = 359ms
 [705] ./app/utils/uploadDataPeriod.js 1.94 kB {0} [built]
       [] -> factory:109ms building:141ms dependencies:0ms = 250ms
 [706] ./app/utils/debugMode.js 3.69 kB {0} [built]
       [] -> factory:16ms building:125ms dependencies:0ms = 141ms
    + 714 hidden modules
Done in 7.83s.

> tidepool-uploader@2.8.4 build-renderer D:\~Development\Source\diabetes\chrome-uploader
> yarn build-renderer-quiet --progress --profile --colors

yarn run v1.12.1
warning package.json: "dependencies" has dependency "eslint-plugin-lodash" with range "2.5.0" that collides with a dependency in "devDependencies" of the same name with version "2.7.0"
$ cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.production.js --progress --profile --colors
Using the default environment, which is now production.
15970ms building modules
31ms sealing
0ms optimizing
0ms basic module optimization
0ms module optimization
0ms advanced module optimization
0ms basic chunk optimization
0ms chunk optimization
0ms advanced chunk optimization
0ms module and chunk tree optimization
0ms chunk modules optimization
0ms advanced chunk modules optimization
16ms module reviving
0ms module order optimization
0ms module id optimization
0ms chunk reviving
0ms chunk order optimization
31ms chunk id optimization
31ms hashing
0ms module assets processing
94ms chunk assets processing
0ms additional chunk assets processing
0ms recording
0ms additional asset processing
2816ms chunk asset optimization
172ms asset optimization
406ms emitting
Hash: 9994f962547eed42d8a8
Version: webpack 3.8.1
Time: 19598ms
                                Asset      Size  Chunks                    Chunk Names
71c4b3129c1b036c625882343856515f.woff   14.6 kB          [emitted]
3ccbd41bfd4962b57199a8fcfbcbde66.woff   14.5 kB          [emitted]
0ffd6c9760dbd98b33b40cda7c5fe855.woff   15.8 kB          [emitted]
84b1d9bb65b585d4b4a72ee9cefb2ac2.woff   15.5 kB          [emitted]
                            bundle.js   7.25 MB       0  [emitted]  [big]  main
                            style.css   24.9 kB       0  [emitted]         main
                        bundle.js.map   8.29 MB       0  [emitted]         main
                        style.css.map  86 bytes       0  [emitted]         main
                          ../app.html   1.06 kB          [emitted]
  [60] (webpack)/buildin/module.js 495 bytes {0} [built]
       [] -> factory:0ms building:0ms = 0ms
  [84] ./app/constants/errors.js 2.44 kB {0} [built]
       [] -> factory:109ms building:172ms = 281ms
 [138] ./lib/config.js 1.21 kB {0} [built]
       [] -> factory:32ms building:156ms = 188ms
 [151] ./lib/core/api.js 20.6 kB {0} [built]
       [] -> factory:32ms building:546ms dependencies:1824ms = 2402ms
 [198] ./app/utils/rollbar.js 1.35 kB {0} [built]
       [] -> factory:32ms building:140ms = 172ms
 [493] multi babel-polyfill ./app/index 40 bytes {0} [built]
        factory:0ms building:0ms = 0ms
 [696] ./app/index.js 3.1 kB {0} [built]
       [] -> factory:453ms building:156ms = 609ms
 [745] ./app/store/configureStore.js 263 bytes {0} [built]
       [] -> factory:32ms building:156ms = 188ms
 [946] ./app/containers/App.js 34.7 kB {0} [built]
       [] -> factory:32ms building:375ms dependencies:4019ms = 4426ms
[1120] ./app/containers/SettingsPage.js 30.1 kB {0} [built]
       [] -> factory:2183ms building:899ms dependencies:2878ms = 5960ms
[1124] ./app/containers/ClinicUserSelectPage.js 21.5 kB {0} [built]
       [] -> factory:2167ms building:836ms dependencies:438ms = 3441ms
[1129] ./app/containers/ClinicUserEditPage.js 27 kB {0} [built]
       [] -> factory:2167ms building:711ms dependencies:657ms = 3535ms
[1133] ./app/containers/NoUploadTargetsPage.js 20.8 kB {0} [built]
       [] -> factory:2167ms building:271ms dependencies:1440ms = 3878ms
[1165] ./app/app.global.css 41 bytes {0} [built]
       [] -> factory:1016ms building:1027ms = 2043ms
[1166] ./styles/main.less 41 bytes {0} [built]
       [] -> factory:1032ms building:7937ms = 8969ms
    + 1152 hidden modules

ERROR in RollbarSourceMapPlugin: required field, 'accessToken', is missing.
Child html-webpack-plugin for "..\app.html":
     1 asset
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./app/app.html 1.34 kB {0} [built]
            factory:125ms building:31ms = 156ms
       [2] (webpack)/buildin/module.js 495 bytes {0} [built]
           [] -> factory:172ms building:47ms = 219ms
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!app/app.global.css:
       [0] ./node_modules/css-loader!./app/app.global.css 159 bytes {0} [built]
            factory:125ms building:605ms = 730ms
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/less-loader/dist/cjs.js!styles/main.less:
                                    Asset     Size  Chunks             Chunk Names
    71c4b3129c1b036c625882343856515f.woff  14.6 kB          [emitted]
    3ccbd41bfd4962b57199a8fcfbcbde66.woff  14.5 kB          [emitted]
    0ffd6c9760dbd98b33b40cda7c5fe855.woff  15.8 kB          [emitted]
    84b1d9bb65b585d4b4a72ee9cefb2ac2.woff  15.5 kB          [emitted]
       [0] ./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js!./styles/main.less 17.5 kB {0} [built]
            factory:468ms building:2910ms = 3378ms
       [3] ./fonts/icons.woff 8.26 kB {0} [built]
           [] -> factory:2561ms building:1967ms = 4528ms
       [4] ./fonts/opensans.woff 83 bytes {0} [built]
           [] -> factory:2561ms building:1998ms = 4559ms
       [5] ./fonts/opensans-bold.woff 83 bytes {0} [built]
           [] -> factory:2561ms building:1982ms = 4543ms
       [6] ./fonts/opensans-italic.woff 83 bytes {0} [built]
           [] -> factory:2561ms building:1998ms = 4559ms
       [7] ./fonts/opensans-bolditalic.woff 83 bytes {0} [built]
           [] -> factory:2561ms building:1998ms = 4559ms
        + 2 hidden modules
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tidepool-uploader@2.8.4 build-renderer: `yarn build-renderer-quiet --progress --profile --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tidepool-uploader@2.8.4 build-renderer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jalad\AppData\Roaming\npm-cache\_logs\2018-11-16T03_06_05_939Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tidepool-uploader@2.8.4 build: `npm run build-main && npm run build-renderer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tidepool-uploader@2.8.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jalad\AppData\Roaming\npm-cache\_logs\2018-11-16T03_06_05_985Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tidepool-uploader@2.8.4 package-win: `npm run build && electron-builder --win --x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tidepool-uploader@2.8.4 package-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jalad\AppData\Roaming\npm-cache\_logs\2018-11-16T03_06_06_033Z-debug.log

**Comment by pazaan** [comment]
Referring to the error:
```
ERROR in RollbarSourceMapPlugin: required field, 'accessToken', is missing.
Child html-webpack-plugin for "..\app.html":
```
You don't have an access token for Rollbar, so it's not able to build the Rollbar integration in the app.
If you would like to just run the uploader to develop against it, you can [follow the setup instructions in the README](https://github.com/tidepool-org/chrome-uploader#how-to-set-it-up).

**Comment by pazaan** [comment]
@gniezen @krystophv - are the npm `package*` targets intended for use by contributors? If so, it seems we should fix this (ie, build without Rollbar support if packaged by contributors), or throw an error when `process.env.ROLLBAR_POST_TOKEN` is not set to state that these build targets are intended for Tidepool use only.

**Comment by pazaan** [comment]
@krystophv okay, cool. @pradeepjaladi - it seems that packing the chrome-uploader outside of our CI environment is not supported. Is there a reason you wish to do this, other than just running `yarn dev`?

**Comment by pradeepjaladi** [comment]
Hi Lennart,

I am developing Health management systems with multiple integrations, One of the integration is upload Diabetes devices data, When i was googling around found about you, So thought of downloading and built it and see how it works.

We are planning to go commerical with your  HMS systems ( Not public yet ) currently working on abott, accucheck, arkay, ascensia, menarini and onetouch meters developing in Java.

Please let me know if i can help in any ways.

**Comment by pazaan** [comment]
All of our device code is in JavaScript. These devices that you're developing support for - do they have protocol specs that are openly shareable? Will your code also be open source?

**Comment by gniezen** [comment]
I added a card to support building a package locally without Rollbar (https://trello.com/c/QtHXeFJv) as it can be useful for example when testing the USB driver installation, or when GitHub is down and the CI webhooks aren't working.

In the meanwhile, I would also suggest to just use `yarn dev` to build and run the uploader instead.

**Comment by pradeepjaladi** [comment]
Hi,

Sorry for replying back so late. If you are looking for specs or implementation for the meters please see the source code of https://sourceforge.net/projects/ggc/
