### ISSUE TITLE
Tandem pump does not upload. Just a blank screen.

### ISSUE THREAD

**Issue by EatOatmeal** [tidepool-org/chrome-uploader#750]
Installed the uploader and only get a blank screen when trying to upload a Tandem pump. Have reinstalled, logged in, tried different computers, tried different connections. Any assistance would be nice.

**Comment by NRiggall** [comment]
Hello, @EatOatmeal!

Thank you for your note. For this and any future support inquiries you have, please email us directly at support@tidepool.org. 

We do not offer active support via Github Issues at this time, but we are working very hard to provide fast support if you reach out to us directly. 

In this case, when you write us an email, may I know your Computer OS Version, installed Tidepool Uploader Version (in the bottom of the window), and potentially a screenshot of the "blank screen" if you are able! (We would expect an error to appear in this case, and we may have one in the logging on our end, which I can check once I know your email address.)

Thank you,
Nick
